### ISSUE TITLE
erlang-r14

### ISSUE THREAD

**Issue by andreineculau** [Homebrew/homebrew-versions#594] opened 2014-12-16 19:10 UTC
fails to install on 10.10

```
Undefined symbols for architecture x86_64:
  "_bp_sched2ix", referenced from:
      _load_nif_2 in erl_nif.o
ld: symbol(s) not found for architecture x86_64
```

refs:

* https://github.com/burbas/erlang-embedded/blob/master/README_IOS.md#bp_sched2ix-function-not-defined
* https://github.com/mrallen1/erlbrew/blob/master/erlbrew#L211

**Comment by L2G** [comment] 2015-02-01 05:15
I am seeing this happen in Mavericks (10.9.5) as well.

[A thread from the erlang-questions mailing list](http://erlang.org/pipermail/erlang-questions/2014-February/076876.html) indicated that gcc-4.2 is more reliable than clang. Maybe the formula needs `fails_with :clang` as well as `fails_with :llvm`. (I'm experimenting with that as I type this.)

**Comment by L2G** [comment] 2015-02-01 20:33
I can confirm that `brew install erlang-r14 --cc=gcc-4.2` works for me on Mavericks (with apple-gcc42 installed).

**Comment by L2G** [comment] 2015-02-02 04:37
The patch that @andreineculau pointed out from the Erlbrew project seems to work great. I was able to build erlang-r14 with both llvm-gcc and clang. See PR #638.

**Comment by DomT4** [comment] 2015-03-10 04:33
Closing in favour of the PR by @L2G which will be merged in the near future (At some point this week - Just ironing out some bottle issues).

**Closed by DomT4** 2015-03-10 04:33 UTC
