### ISSUE TITLE
Mono3, download fails

### ISSUE THREAD

**Issue by HaraldNordgren** [Homebrew/homebrew-versions#1503] opened 2017-01-02 01:26 UTC
```
$ brew install --verbose homebrew/versions/mono3
==> Installing mono3 from homebrew/versions
==> Downloading http://download.mono-project.com/sources/mono/mono-3.12.1.tar.bz2
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.5 (Macintosh; Intel macOS 10.12.1) curl/7.49.1 http://download.mono-project.com/sources/mono/mono-3.12.1.tar.bz2 -C 0 -o /Users/travis/Library/Caches/Homebrew/mono3-3.12.1.tar.bz2.incomplete --silent
==> Verifying mono3-3.12.1.tar.bz2 checksum
tar xjf /Users/travis/Library/Caches/Homebrew/mono3-3.12.1.tar.bz2
==> Downloading http://storage.bos.xamarin.com/mono-dist-master/cb/cb33b94c853049a43222288ead1e0cb059b22783/monolite-111-latest.tar.gz
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.5 (Macintosh; Intel macOS 10.12.1) curl/7.49.1 http://storage.bos.xamarin.com/mono-dist-master/cb/cb33b94c853049a43222288ead1e0cb059b22783/monolite-111-latest.tar.gz -C 0 -o /Users/travis/Library/Caches/Homebrew/mono3--monolite-111.tar.gz.incomplete --silent
Error: Failed to download resource "mono3--monolite"
Download failed: http://storage.bos.xamarin.com/mono-dist-master/cb/cb33b94c853049a43222288ead1e0cb059b22783/monolite-111-latest.tar.gz
```

Calling `wget http://storage.bos.xamarin.com/mono-dist-master/cb/cb33b94c853049a43222288ead1e0cb059b22783/monolite-111-latest.tar.gz` seems to verify that the desired host is not accessible.

**Comment by MikeMcQuaid** [comment] 2017-01-02 20:19
Duplicate of https://github.com/Homebrew/homebrew-versions/issues/1401

**Closed by MikeMcQuaid** 2017-01-02 20:19 UTC
